
package lw.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Service_mbSoap", targetNamespace = "Service_mb")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceMbSoap {


    /**
     * 
     * @param birthdate
     * @param birthcity
     * @param city
     * @param mobileNumber
     * @param companyName
     * @param clientTitle
     * @param language
     * @param isDebtor
     * @param clientMail
     * @param payerOrBeneficiary
     * @param walletIp
     * @param street
     * @param ctry
     * @param birthcountry
     * @param companyIdentificationNumber
     * @param clientLastName
     * @param wallet
     * @param companyDescription
     * @param wlLogin
     * @param isCompany
     * @param version
     * @param wlPass
     * @param walletUa
     * @param phoneNumber
     * @param nationality
     * @param clientFirstName
     * @param isOneTimeCustomer
     * @param postCode
     * @param companyWebsite
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RegisterWallet", action = "Service_mb/RegisterWallet")
    @WebResult(name = "RegisterWalletResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "RegisterWallet", targetNamespace = "Service_mb", className = "lw.api.RegisterWallet")
    @ResponseWrapper(localName = "RegisterWalletResponse", targetNamespace = "Service_mb", className = "lw.api.RegisterWalletResponse")
    public String registerWallet(
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "clientMail", targetNamespace = "Service_mb")
        String clientMail,
        @WebParam(name = "clientTitle", targetNamespace = "Service_mb")
        String clientTitle,
        @WebParam(name = "clientFirstName", targetNamespace = "Service_mb")
        String clientFirstName,
        @WebParam(name = "clientLastName", targetNamespace = "Service_mb")
        String clientLastName,
        @WebParam(name = "phoneNumber", targetNamespace = "Service_mb")
        String phoneNumber,
        @WebParam(name = "mobileNumber", targetNamespace = "Service_mb")
        String mobileNumber,
        @WebParam(name = "street", targetNamespace = "Service_mb")
        String street,
        @WebParam(name = "postCode", targetNamespace = "Service_mb")
        String postCode,
        @WebParam(name = "city", targetNamespace = "Service_mb")
        String city,
        @WebParam(name = "ctry", targetNamespace = "Service_mb")
        String ctry,
        @WebParam(name = "birthdate", targetNamespace = "Service_mb")
        String birthdate,
        @WebParam(name = "isCompany", targetNamespace = "Service_mb")
        String isCompany,
        @WebParam(name = "companyName", targetNamespace = "Service_mb")
        String companyName,
        @WebParam(name = "companyWebsite", targetNamespace = "Service_mb")
        String companyWebsite,
        @WebParam(name = "companyDescription", targetNamespace = "Service_mb")
        String companyDescription,
        @WebParam(name = "isDebtor", targetNamespace = "Service_mb")
        String isDebtor,
        @WebParam(name = "nationality", targetNamespace = "Service_mb")
        String nationality,
        @WebParam(name = "birthcity", targetNamespace = "Service_mb")
        String birthcity,
        @WebParam(name = "birthcountry", targetNamespace = "Service_mb")
        String birthcountry,
        @WebParam(name = "companyIdentificationNumber", targetNamespace = "Service_mb")
        String companyIdentificationNumber,
        @WebParam(name = "payerOrBeneficiary", targetNamespace = "Service_mb")
        String payerOrBeneficiary,
        @WebParam(name = "isOneTimeCustomer", targetNamespace = "Service_mb")
        String isOneTimeCustomer,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param newMobileNumber
     * @param newCompanyName
     * @param newBirthDate
     * @param language
     * @param newFirstName
     * @param newCtry
     * @param newIsCompany
     * @param newPostCode
     * @param walletIp
     * @param newCity
     * @param newIp
     * @param newCompanyDescription
     * @param newTitle
     * @param newCompanyIdentificationNumber
     * @param wallet
     * @param newBirthcountry
     * @param wlLogin
     * @param newLastName
     * @param version
     * @param wlPass
     * @param newCompanyWebsite
     * @param walletUa
     * @param newPhoneNumber
     * @param newIsDebtor
     * @param newNationality
     * @param newBirthcity
     * @param newEmail
     * @param newStreet
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdateWalletDetails", action = "Service_mb/UpdateWalletDetails")
    @WebResult(name = "UpdateWalletDetailsResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "UpdateWalletDetails", targetNamespace = "Service_mb", className = "lw.api.UpdateWalletDetails")
    @ResponseWrapper(localName = "UpdateWalletDetailsResponse", targetNamespace = "Service_mb", className = "lw.api.UpdateWalletDetailsResponse")
    public String updateWalletDetails(
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "newEmail", targetNamespace = "Service_mb")
        String newEmail,
        @WebParam(name = "newTitle", targetNamespace = "Service_mb")
        String newTitle,
        @WebParam(name = "newFirstName", targetNamespace = "Service_mb")
        String newFirstName,
        @WebParam(name = "newLastName", targetNamespace = "Service_mb")
        String newLastName,
        @WebParam(name = "newStreet", targetNamespace = "Service_mb")
        String newStreet,
        @WebParam(name = "newPostCode", targetNamespace = "Service_mb")
        String newPostCode,
        @WebParam(name = "newCity", targetNamespace = "Service_mb")
        String newCity,
        @WebParam(name = "newCtry", targetNamespace = "Service_mb")
        String newCtry,
        @WebParam(name = "newIp", targetNamespace = "Service_mb")
        String newIp,
        @WebParam(name = "newPhoneNumber", targetNamespace = "Service_mb")
        String newPhoneNumber,
        @WebParam(name = "newMobileNumber", targetNamespace = "Service_mb")
        String newMobileNumber,
        @WebParam(name = "newBirthDate", targetNamespace = "Service_mb")
        String newBirthDate,
        @WebParam(name = "newIsCompany", targetNamespace = "Service_mb")
        String newIsCompany,
        @WebParam(name = "newCompanyName", targetNamespace = "Service_mb")
        String newCompanyName,
        @WebParam(name = "newCompanyWebsite", targetNamespace = "Service_mb")
        String newCompanyWebsite,
        @WebParam(name = "newCompanyDescription", targetNamespace = "Service_mb")
        String newCompanyDescription,
        @WebParam(name = "newIsDebtor", targetNamespace = "Service_mb")
        String newIsDebtor,
        @WebParam(name = "newNationality", targetNamespace = "Service_mb")
        String newNationality,
        @WebParam(name = "newBirthcity", targetNamespace = "Service_mb")
        String newBirthcity,
        @WebParam(name = "newBirthcountry", targetNamespace = "Service_mb")
        String newBirthcountry,
        @WebParam(name = "newCompanyIdentificationNumber", targetNamespace = "Service_mb")
        String newCompanyIdentificationNumber,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param walletUa
     * @param wallet
     * @param newStatus
     * @param walletIp
     * @param wlLogin
     * @param language
     * @param version
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdateWalletStatus", action = "Service_mb/UpdateWalletStatus")
    @WebResult(name = "UpdateWalletStatusResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "UpdateWalletStatus", targetNamespace = "Service_mb", className = "lw.api.UpdateWalletStatus")
    @ResponseWrapper(localName = "UpdateWalletStatusResponse", targetNamespace = "Service_mb", className = "lw.api.UpdateWalletStatusResponse")
    public String updateWalletStatus(
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "newStatus", targetNamespace = "Service_mb")
        String newStatus,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param dom1
     * @param wallet
     * @param wlLogin
     * @param holder
     * @param language
     * @param version
     * @param wlPass
     * @param walletUa
     * @param walletIp
     * @param iban
     * @param ignoreIbanFormat
     * @param comment
     * @param bic
     * @param dom2
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RegisterIBAN", action = "Service_mb/RegisterIBAN")
    @WebResult(name = "RegisterIBANResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "RegisterIBAN", targetNamespace = "Service_mb", className = "lw.api.RegisterIBAN")
    @ResponseWrapper(localName = "RegisterIBANResponse", targetNamespace = "Service_mb", className = "lw.api.RegisterIBANResponse")
    public String registerIBAN(
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "holder", targetNamespace = "Service_mb")
        String holder,
        @WebParam(name = "bic", targetNamespace = "Service_mb")
        String bic,
        @WebParam(name = "iban", targetNamespace = "Service_mb")
        String iban,
        @WebParam(name = "dom1", targetNamespace = "Service_mb")
        String dom1,
        @WebParam(name = "dom2", targetNamespace = "Service_mb")
        String dom2,
        @WebParam(name = "comment", targetNamespace = "Service_mb")
        String comment,
        @WebParam(name = "ignoreIbanFormat", targetNamespace = "Service_mb")
        String ignoreIbanFormat,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param intermediaryBankCountry
     * @param holderName
     * @param wallet
     * @param accountType
     * @param wlLogin
     * @param holderCountry
     * @param intermediaryBankName
     * @param bankName
     * @param language
     * @param bicCode
     * @param accountNumber
     * @param version
     * @param intermediaryBicCode
     * @param wlPass
     * @param bankCountry
     * @param walletUa
     * @param walletIp
     * @param comment
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RegisterIBANExtended", action = "Service_mb/RegisterIBANExtended")
    @WebResult(name = "RegisterIBANExtendedResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "RegisterIBANExtended", targetNamespace = "Service_mb", className = "lw.api.RegisterIBANExtended")
    @ResponseWrapper(localName = "RegisterIBANExtendedResponse", targetNamespace = "Service_mb", className = "lw.api.RegisterIBANExtendedResponse")
    public String registerIBANExtended(
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "accountType", targetNamespace = "Service_mb")
        String accountType,
        @WebParam(name = "holderName", targetNamespace = "Service_mb")
        String holderName,
        @WebParam(name = "accountNumber", targetNamespace = "Service_mb")
        String accountNumber,
        @WebParam(name = "holderCountry", targetNamespace = "Service_mb")
        String holderCountry,
        @WebParam(name = "bicCode", targetNamespace = "Service_mb")
        String bicCode,
        @WebParam(name = "bankName", targetNamespace = "Service_mb")
        String bankName,
        @WebParam(name = "bankCountry", targetNamespace = "Service_mb")
        String bankCountry,
        @WebParam(name = "intermediaryBicCode", targetNamespace = "Service_mb")
        String intermediaryBicCode,
        @WebParam(name = "intermediaryBankName", targetNamespace = "Service_mb")
        String intermediaryBankName,
        @WebParam(name = "intermediaryBankCountry", targetNamespace = "Service_mb")
        String intermediaryBankCountry,
        @WebParam(name = "comment", targetNamespace = "Service_mb")
        String comment,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param country
     * @param mandateLanguage
     * @param wallet
     * @param city
     * @param wlLogin
     * @param holder
     * @param isRecurring
     * @param language
     * @param version
     * @param wlPass
     * @param walletUa
     * @param isB2B
     * @param walletIp
     * @param street
     * @param iban
     * @param postCode
     * @param bic
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RegisterSddMandate", action = "Service_mb/RegisterSddMandate")
    @WebResult(name = "RegisterSddMandateResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "RegisterSddMandate", targetNamespace = "Service_mb", className = "lw.api.RegisterSddMandate")
    @ResponseWrapper(localName = "RegisterSddMandateResponse", targetNamespace = "Service_mb", className = "lw.api.RegisterSddMandateResponse")
    public String registerSddMandate(
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "holder", targetNamespace = "Service_mb")
        String holder,
        @WebParam(name = "bic", targetNamespace = "Service_mb")
        String bic,
        @WebParam(name = "iban", targetNamespace = "Service_mb")
        String iban,
        @WebParam(name = "isRecurring", targetNamespace = "Service_mb")
        String isRecurring,
        @WebParam(name = "street", targetNamespace = "Service_mb")
        String street,
        @WebParam(name = "postCode", targetNamespace = "Service_mb")
        String postCode,
        @WebParam(name = "city", targetNamespace = "Service_mb")
        String city,
        @WebParam(name = "country", targetNamespace = "Service_mb")
        String country,
        @WebParam(name = "mandateLanguage", targetNamespace = "Service_mb")
        String mandateLanguage,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa,
        @WebParam(name = "isB2B", targetNamespace = "Service_mb")
        String isB2B);

    /**
     * 
     * @param walletUa
     * @param wallet
     * @param cardDate
     * @param specialConfig
     * @param walletIp
     * @param cardCode
     * @param wlLogin
     * @param cardType
     * @param language
     * @param version
     * @param cardNumber
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RegisterCard", action = "Service_mb/RegisterCard")
    @WebResult(name = "RegisterCardResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "RegisterCard", targetNamespace = "Service_mb", className = "lw.api.RegisterCard")
    @ResponseWrapper(localName = "RegisterCardResponse", targetNamespace = "Service_mb", className = "lw.api.RegisterCardResponse")
    public String registerCard(
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "cardType", targetNamespace = "Service_mb")
        String cardType,
        @WebParam(name = "cardNumber", targetNamespace = "Service_mb")
        String cardNumber,
        @WebParam(name = "cardCode", targetNamespace = "Service_mb")
        String cardCode,
        @WebParam(name = "cardDate", targetNamespace = "Service_mb")
        String cardDate,
        @WebParam(name = "specialConfig", targetNamespace = "Service_mb")
        String specialConfig,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param walletUa
     * @param wallet
     * @param walletIp
     * @param cardId
     * @param wlLogin
     * @param language
     * @param version
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UnregisterCard", action = "Service_mb/UnregisterCard")
    @WebResult(name = "UnregisterCardResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "UnregisterCard", targetNamespace = "Service_mb", className = "lw.api.UnregisterCard")
    @ResponseWrapper(localName = "UnregisterCardResponse", targetNamespace = "Service_mb", className = "lw.api.UnregisterCardResponse")
    public String unregisterCard(
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "cardId", targetNamespace = "Service_mb")
        String cardId,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param walletUa
     * @param wallet
     * @param walletIp
     * @param wlLogin
     * @param sddMandateId
     * @param language
     * @param version
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UnregisterSddMandate", action = "Service_mb/UnregisterSddMandate")
    @WebResult(name = "UnregisterSddMandateResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "UnregisterSddMandate", targetNamespace = "Service_mb", className = "lw.api.UnregisterSddMandate")
    @ResponseWrapper(localName = "UnregisterSddMandateResponse", targetNamespace = "Service_mb", className = "lw.api.UnregisterSddMandateResponse")
    public String unregisterSddMandate(
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "sddMandateId", targetNamespace = "Service_mb")
        String sddMandateId,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param wallet
     * @param isPreAuth
     * @param cardDate
     * @param amountCom
     * @param specialConfig
     * @param wlLogin
     * @param cardType
     * @param wkToken
     * @param language
     * @param cardCrypto
     * @param amountTot
     * @param autoCommission
     * @param version
     * @param wlPass
     * @param walletUa
     * @param delayedDays
     * @param walletIp
     * @param comment
     * @param cardNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MoneyIn", action = "Service_mb/MoneyIn")
    @WebResult(name = "MoneyInResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "MoneyIn", targetNamespace = "Service_mb", className = "lw.api.MoneyIn")
    @ResponseWrapper(localName = "MoneyInResponse", targetNamespace = "Service_mb", className = "lw.api.MoneyInResponse")
    public String moneyIn(
        @WebParam(name = "wkToken", targetNamespace = "Service_mb")
        String wkToken,
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "amountTot", targetNamespace = "Service_mb")
        String amountTot,
        @WebParam(name = "amountCom", targetNamespace = "Service_mb")
        String amountCom,
        @WebParam(name = "comment", targetNamespace = "Service_mb")
        String comment,
        @WebParam(name = "cardType", targetNamespace = "Service_mb")
        String cardType,
        @WebParam(name = "cardNumber", targetNamespace = "Service_mb")
        String cardNumber,
        @WebParam(name = "cardCrypto", targetNamespace = "Service_mb")
        String cardCrypto,
        @WebParam(name = "cardDate", targetNamespace = "Service_mb")
        String cardDate,
        @WebParam(name = "autoCommission", targetNamespace = "Service_mb")
        String autoCommission,
        @WebParam(name = "isPreAuth", targetNamespace = "Service_mb")
        String isPreAuth,
        @WebParam(name = "specialConfig", targetNamespace = "Service_mb")
        String specialConfig,
        @WebParam(name = "delayedDays", targetNamespace = "Service_mb")
        String delayedDays,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param walletUa
     * @param amountCom
     * @param specialConfig
     * @param walletIp
     * @param wlLogin
     * @param language
     * @param amountTot
     * @param version
     * @param transactionId
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MoneyInValidate", action = "Service_mb/MoneyInValidate")
    @WebResult(name = "MoneyInValidateResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "MoneyInValidate", targetNamespace = "Service_mb", className = "lw.api.MoneyInValidate")
    @ResponseWrapper(localName = "MoneyInValidateResponse", targetNamespace = "Service_mb", className = "lw.api.MoneyInValidateResponse")
    public String moneyInValidate(
        @WebParam(name = "transactionId", targetNamespace = "Service_mb")
        String transactionId,
        @WebParam(name = "amountTot", targetNamespace = "Service_mb")
        String amountTot,
        @WebParam(name = "amountCom", targetNamespace = "Service_mb")
        String amountCom,
        @WebParam(name = "specialConfig", targetNamespace = "Service_mb")
        String specialConfig,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param walletUa
     * @param walletIp
     * @param wlLogin
     * @param language
     * @param version
     * @param transactionId
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CancelScheduledP2P", action = "Service_mb/CancelScheduledP2P")
    @WebResult(name = "CancelScheduledP2PResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "CancelScheduledP2P", targetNamespace = "Service_mb", className = "lw.api.CancelScheduledP2P")
    @ResponseWrapper(localName = "CancelScheduledP2PResponse", targetNamespace = "Service_mb", className = "lw.api.CancelScheduledP2PResponse")
    public String cancelScheduledP2P(
        @WebParam(name = "transactionId", targetNamespace = "Service_mb")
        String transactionId,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param wallet
     * @param cardDate
     * @param amountCom
     * @param cardCode
     * @param wlLogin
     * @param cardType
     * @param wkToken
     * @param language
     * @param amountTot
     * @param autoCommission
     * @param version
     * @param wlPass
     * @param walletUa
     * @param walletIp
     * @param comment
     * @param returnUrl
     * @param cardNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MoneyIn3DInit", action = "Service_mb/MoneyIn3DInit")
    @WebResult(name = "MoneyIn3DInitResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "MoneyIn3DInit", targetNamespace = "Service_mb", className = "lw.api.MoneyIn3DInit")
    @ResponseWrapper(localName = "MoneyIn3DInitResponse", targetNamespace = "Service_mb", className = "lw.api.MoneyIn3DInitResponse")
    public String moneyIn3DInit(
        @WebParam(name = "wkToken", targetNamespace = "Service_mb")
        String wkToken,
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "amountTot", targetNamespace = "Service_mb")
        String amountTot,
        @WebParam(name = "amountCom", targetNamespace = "Service_mb")
        String amountCom,
        @WebParam(name = "comment", targetNamespace = "Service_mb")
        String comment,
        @WebParam(name = "cardType", targetNamespace = "Service_mb")
        String cardType,
        @WebParam(name = "cardNumber", targetNamespace = "Service_mb")
        String cardNumber,
        @WebParam(name = "cardCode", targetNamespace = "Service_mb")
        String cardCode,
        @WebParam(name = "cardDate", targetNamespace = "Service_mb")
        String cardDate,
        @WebParam(name = "autoCommission", targetNamespace = "Service_mb")
        String autoCommission,
        @WebParam(name = "returnUrl", targetNamespace = "Service_mb")
        String returnUrl,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param isPreAuth
     * @param cardDate
     * @param specialConfig
     * @param cardCode
     * @param wlLogin
     * @param cardType
     * @param language
     * @param version
     * @param transactionId
     * @param wlPass
     * @param walletUa
     * @param delayedDays
     * @param walletIp
     * @param md
     * @param paRes
     * @param cardNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MoneyIn3DConfirm", action = "Service_mb/MoneyIn3DConfirm")
    @WebResult(name = "MoneyIn3DConfirmResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "MoneyIn3DConfirm", targetNamespace = "Service_mb", className = "lw.api.MoneyIn3DConfirm")
    @ResponseWrapper(localName = "MoneyIn3DConfirmResponse", targetNamespace = "Service_mb", className = "lw.api.MoneyIn3DConfirmResponse")
    public String moneyIn3DConfirm(
        @WebParam(name = "transactionId", targetNamespace = "Service_mb")
        String transactionId,
        @WebParam(name = "MD", targetNamespace = "Service_mb")
        String md,
        @WebParam(name = "PaRes", targetNamespace = "Service_mb")
        String paRes,
        @WebParam(name = "cardType", targetNamespace = "Service_mb")
        String cardType,
        @WebParam(name = "cardNumber", targetNamespace = "Service_mb")
        String cardNumber,
        @WebParam(name = "cardCode", targetNamespace = "Service_mb")
        String cardCode,
        @WebParam(name = "cardDate", targetNamespace = "Service_mb")
        String cardDate,
        @WebParam(name = "isPreAuth", targetNamespace = "Service_mb")
        String isPreAuth,
        @WebParam(name = "specialConfig", targetNamespace = "Service_mb")
        String specialConfig,
        @WebParam(name = "delayedDays", targetNamespace = "Service_mb")
        String delayedDays,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param cardDate
     * @param specialConfig
     * @param cardCode
     * @param wlLogin
     * @param cardType
     * @param language
     * @param version
     * @param transactionId
     * @param wlPass
     * @param walletUa
     * @param walletIp
     * @param md
     * @param paRes
     * @param cardNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MoneyIn3DAuthenticate", action = "Service_mb/MoneyIn3DAuthenticate")
    @WebResult(name = "MoneyIn3DAuthenticateResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "MoneyIn3DAuthenticate", targetNamespace = "Service_mb", className = "lw.api.MoneyIn3DAuthenticate")
    @ResponseWrapper(localName = "MoneyIn3DAuthenticateResponse", targetNamespace = "Service_mb", className = "lw.api.MoneyIn3DAuthenticateResponse")
    public String moneyIn3DAuthenticate(
        @WebParam(name = "transactionId", targetNamespace = "Service_mb")
        String transactionId,
        @WebParam(name = "MD", targetNamespace = "Service_mb")
        String md,
        @WebParam(name = "PaRes", targetNamespace = "Service_mb")
        String paRes,
        @WebParam(name = "cardType", targetNamespace = "Service_mb")
        String cardType,
        @WebParam(name = "cardNumber", targetNamespace = "Service_mb")
        String cardNumber,
        @WebParam(name = "cardCode", targetNamespace = "Service_mb")
        String cardCode,
        @WebParam(name = "cardDate", targetNamespace = "Service_mb")
        String cardDate,
        @WebParam(name = "specialConfig", targetNamespace = "Service_mb")
        String specialConfig,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param wallet
     * @param amountCom
     * @param wlLogin
     * @param wkToken
     * @param language
     * @param amountTot
     * @param useRegisteredCard
     * @param autoCommission
     * @param version
     * @param wlPass
     * @param walletUa
     * @param errorUrl
     * @param cancelUrl
     * @param walletIp
     * @param comment
     * @param returnUrl
     * @param registerCard
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MoneyInWebInit", action = "Service_mb/MoneyInWebInit")
    @WebResult(name = "MoneyInWebInitResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "MoneyInWebInit", targetNamespace = "Service_mb", className = "lw.api.MoneyInWebInit")
    @ResponseWrapper(localName = "MoneyInWebInitResponse", targetNamespace = "Service_mb", className = "lw.api.MoneyInWebInitResponse")
    public String moneyInWebInit(
        @WebParam(name = "wkToken", targetNamespace = "Service_mb")
        String wkToken,
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "amountTot", targetNamespace = "Service_mb")
        String amountTot,
        @WebParam(name = "amountCom", targetNamespace = "Service_mb")
        String amountCom,
        @WebParam(name = "comment", targetNamespace = "Service_mb")
        String comment,
        @WebParam(name = "useRegisteredCard", targetNamespace = "Service_mb")
        String useRegisteredCard,
        @WebParam(name = "returnUrl", targetNamespace = "Service_mb")
        String returnUrl,
        @WebParam(name = "cancelUrl", targetNamespace = "Service_mb")
        String cancelUrl,
        @WebParam(name = "errorUrl", targetNamespace = "Service_mb")
        String errorUrl,
        @WebParam(name = "autoCommission", targetNamespace = "Service_mb")
        String autoCommission,
        @WebParam(name = "registerCard", targetNamespace = "Service_mb")
        String registerCard,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param walletUa
     * @param errorUrl
     * @param wallet
     * @param documentType
     * @param walletIp
     * @param mobileNumber
     * @param wlLogin
     * @param documentId
     * @param language
     * @param returnUrl
     * @param version
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SignDocumentInit", action = "Service_mb/SignDocumentInit")
    @WebResult(name = "SignDocumentInitResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "SignDocumentInit", targetNamespace = "Service_mb", className = "lw.api.SignDocumentInit")
    @ResponseWrapper(localName = "SignDocumentInitResponse", targetNamespace = "Service_mb", className = "lw.api.SignDocumentInitResponse")
    public String signDocumentInit(
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "mobileNumber", targetNamespace = "Service_mb")
        String mobileNumber,
        @WebParam(name = "documentId", targetNamespace = "Service_mb")
        String documentId,
        @WebParam(name = "documentType", targetNamespace = "Service_mb")
        String documentType,
        @WebParam(name = "returnUrl", targetNamespace = "Service_mb")
        String returnUrl,
        @WebParam(name = "errorUrl", targetNamespace = "Service_mb")
        String errorUrl,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param wallet
     * @param isPreAuth
     * @param amountCom
     * @param specialConfig
     * @param wlLogin
     * @param wkToken
     * @param language
     * @param amountTot
     * @param autoCommission
     * @param version
     * @param wlPass
     * @param walletUa
     * @param delayedDays
     * @param walletIp
     * @param cardId
     * @param comment
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MoneyInWithCardId", action = "Service_mb/MoneyInWithCardId")
    @WebResult(name = "MoneyInWithCardIdResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "MoneyInWithCardId", targetNamespace = "Service_mb", className = "lw.api.MoneyInWithCardId")
    @ResponseWrapper(localName = "MoneyInWithCardIdResponse", targetNamespace = "Service_mb", className = "lw.api.MoneyInWithCardIdResponse")
    public String moneyInWithCardId(
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "amountTot", targetNamespace = "Service_mb")
        String amountTot,
        @WebParam(name = "amountCom", targetNamespace = "Service_mb")
        String amountCom,
        @WebParam(name = "comment", targetNamespace = "Service_mb")
        String comment,
        @WebParam(name = "cardId", targetNamespace = "Service_mb")
        String cardId,
        @WebParam(name = "autoCommission", targetNamespace = "Service_mb")
        String autoCommission,
        @WebParam(name = "isPreAuth", targetNamespace = "Service_mb")
        String isPreAuth,
        @WebParam(name = "specialConfig", targetNamespace = "Service_mb")
        String specialConfig,
        @WebParam(name = "wkToken", targetNamespace = "Service_mb")
        String wkToken,
        @WebParam(name = "delayedDays", targetNamespace = "Service_mb")
        String delayedDays,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param privateData
     * @param walletUa
     * @param amount
     * @param walletIp
     * @param wlLogin
     * @param scheduledDate
     * @param debitWallet
     * @param language
     * @param message
     * @param version
     * @param wlPass
     * @param creditWallet
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendPayment", action = "Service_mb/SendPayment")
    @WebResult(name = "SendPaymentResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "SendPayment", targetNamespace = "Service_mb", className = "lw.api.SendPayment")
    @ResponseWrapper(localName = "SendPaymentResponse", targetNamespace = "Service_mb", className = "lw.api.SendPaymentResponse")
    public String sendPayment(
        @WebParam(name = "debitWallet", targetNamespace = "Service_mb")
        String debitWallet,
        @WebParam(name = "creditWallet", targetNamespace = "Service_mb")
        String creditWallet,
        @WebParam(name = "amount", targetNamespace = "Service_mb")
        String amount,
        @WebParam(name = "message", targetNamespace = "Service_mb")
        String message,
        @WebParam(name = "scheduledDate", targetNamespace = "Service_mb")
        String scheduledDate,
        @WebParam(name = "privateData", targetNamespace = "Service_mb")
        String privateData,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param privateData
     * @param walletUa
     * @param transactionComment
     * @param walletIp
     * @param wlLogin
     * @param language
     * @param version
     * @param transactionId
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPaymentDetails", action = "Service_mb/GetPaymentDetails")
    @WebResult(name = "GetPaymentDetailsResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "GetPaymentDetails", targetNamespace = "Service_mb", className = "lw.api.GetPaymentDetails")
    @ResponseWrapper(localName = "GetPaymentDetailsResponse", targetNamespace = "Service_mb", className = "lw.api.GetPaymentDetailsResponse")
    public String getPaymentDetails(
        @WebParam(name = "transactionId", targetNamespace = "Service_mb")
        String transactionId,
        @WebParam(name = "transactionComment", targetNamespace = "Service_mb")
        String transactionComment,
        @WebParam(name = "privateData", targetNamespace = "Service_mb")
        String privateData,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param walletUa
     * @param transactionComment
     * @param endDate
     * @param walletIp
     * @param wlLogin
     * @param transactionMerchantToken
     * @param language
     * @param version
     * @param transactionId
     * @param startDate
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMoneyInTransDetails", action = "Service_mb/GetMoneyInTransDetails")
    @WebResult(name = "GetMoneyInTransDetailsResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "GetMoneyInTransDetails", targetNamespace = "Service_mb", className = "lw.api.GetMoneyInTransDetails")
    @ResponseWrapper(localName = "GetMoneyInTransDetailsResponse", targetNamespace = "Service_mb", className = "lw.api.GetMoneyInTransDetailsResponse")
    public String getMoneyInTransDetails(
        @WebParam(name = "transactionId", targetNamespace = "Service_mb")
        String transactionId,
        @WebParam(name = "transactionComment", targetNamespace = "Service_mb")
        String transactionComment,
        @WebParam(name = "transactionMerchantToken", targetNamespace = "Service_mb")
        String transactionMerchantToken,
        @WebParam(name = "startDate", targetNamespace = "Service_mb")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "Service_mb")
        String endDate,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param walletUa
     * @param wallet
     * @param endDate
     * @param walletIp
     * @param wlLogin
     * @param language
     * @param version
     * @param startDate
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetWalletTransHistory", action = "Service_mb/GetWalletTransHistory")
    @WebResult(name = "GetWalletTransHistoryResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "GetWalletTransHistory", targetNamespace = "Service_mb", className = "lw.api.GetWalletTransHistory")
    @ResponseWrapper(localName = "GetWalletTransHistoryResponse", targetNamespace = "Service_mb", className = "lw.api.GetWalletTransHistoryResponse")
    public String getWalletTransHistory(
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "startDate", targetNamespace = "Service_mb")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "Service_mb")
        String endDate,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param walletUa
     * @param transactionComment
     * @param walletIp
     * @param wlLogin
     * @param language
     * @param version
     * @param transactionId
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMoneyOutTransDetails", action = "Service_mb/GetMoneyOutTransDetails")
    @WebResult(name = "GetMoneyOutTransDetailsResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "GetMoneyOutTransDetails", targetNamespace = "Service_mb", className = "lw.api.GetMoneyOutTransDetails")
    @ResponseWrapper(localName = "GetMoneyOutTransDetailsResponse", targetNamespace = "Service_mb", className = "lw.api.GetMoneyOutTransDetailsResponse")
    public String getMoneyOutTransDetails(
        @WebParam(name = "transactionId", targetNamespace = "Service_mb")
        String transactionId,
        @WebParam(name = "transactionComment", targetNamespace = "Service_mb")
        String transactionComment,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param walletUa
     * @param wallet
     * @param amountCom
     * @param walletIp
     * @param wlLogin
     * @param language
     * @param message
     * @param amountTot
     * @param autoCommission
     * @param version
     * @param ibanId
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MoneyOut", action = "Service_mb/MoneyOut")
    @WebResult(name = "MoneyOutResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "MoneyOut", targetNamespace = "Service_mb", className = "lw.api.MoneyOut")
    @ResponseWrapper(localName = "MoneyOutResponse", targetNamespace = "Service_mb", className = "lw.api.MoneyOutResponse")
    public String moneyOut(
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "ibanId", targetNamespace = "Service_mb")
        String ibanId,
        @WebParam(name = "amountTot", targetNamespace = "Service_mb")
        String amountTot,
        @WebParam(name = "amountCom", targetNamespace = "Service_mb")
        String amountCom,
        @WebParam(name = "message", targetNamespace = "Service_mb")
        String message,
        @WebParam(name = "autoCommission", targetNamespace = "Service_mb")
        String autoCommission,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param walletUa
     * @param walletIp
     * @param wlLogin
     * @param amountToRefund
     * @param comment
     * @param language
     * @param version
     * @param transactionId
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RefundMoneyIn", action = "Service_mb/RefundMoneyIn")
    @WebResult(name = "RefundMoneyInResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "RefundMoneyIn", targetNamespace = "Service_mb", className = "lw.api.RefundMoneyIn")
    @ResponseWrapper(localName = "RefundMoneyInResponse", targetNamespace = "Service_mb", className = "lw.api.RefundMoneyInResponse")
    public String refundMoneyIn(
        @WebParam(name = "transactionId", targetNamespace = "Service_mb")
        String transactionId,
        @WebParam(name = "amountToRefund", targetNamespace = "Service_mb")
        String amountToRefund,
        @WebParam(name = "comment", targetNamespace = "Service_mb")
        String comment,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param walletUa
     * @param wallet
     * @param walletIp
     * @param wlLogin
     * @param language
     * @param version
     * @param email
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetWalletDetails", action = "Service_mb/GetWalletDetails")
    @WebResult(name = "GetWalletDetailsResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "GetWalletDetails", targetNamespace = "Service_mb", className = "lw.api.GetWalletDetails")
    @ResponseWrapper(localName = "GetWalletDetailsResponse", targetNamespace = "Service_mb", className = "lw.api.GetWalletDetailsResponse")
    public String getWalletDetails(
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "email", targetNamespace = "Service_mb")
        String email,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param clientLastName
     * @param amount
     * @param cardDate
     * @param wlLogin
     * @param clientTitle
     * @param cardType
     * @param language
     * @param cardCrypto
     * @param message
     * @param autoCommission
     * @param version
     * @param wlPass
     * @param clientMail
     * @param walletUa
     * @param walletIp
     * @param clientFirstName
     * @param registerCard
     * @param cardNumber
     * @param creditWallet
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FastPay", action = "Service_mb/FastPay")
    @WebResult(name = "FastPayResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "FastPay", targetNamespace = "Service_mb", className = "lw.api.FastPay")
    @ResponseWrapper(localName = "FastPayResponse", targetNamespace = "Service_mb", className = "lw.api.FastPayResponse")
    public String fastPay(
        @WebParam(name = "clientMail", targetNamespace = "Service_mb")
        String clientMail,
        @WebParam(name = "clientTitle", targetNamespace = "Service_mb")
        String clientTitle,
        @WebParam(name = "clientFirstName", targetNamespace = "Service_mb")
        String clientFirstName,
        @WebParam(name = "clientLastName", targetNamespace = "Service_mb")
        String clientLastName,
        @WebParam(name = "cardType", targetNamespace = "Service_mb")
        String cardType,
        @WebParam(name = "cardNumber", targetNamespace = "Service_mb")
        String cardNumber,
        @WebParam(name = "cardCrypto", targetNamespace = "Service_mb")
        String cardCrypto,
        @WebParam(name = "cardDate", targetNamespace = "Service_mb")
        String cardDate,
        @WebParam(name = "creditWallet", targetNamespace = "Service_mb")
        String creditWallet,
        @WebParam(name = "amount", targetNamespace = "Service_mb")
        String amount,
        @WebParam(name = "message", targetNamespace = "Service_mb")
        String message,
        @WebParam(name = "autoCommission", targetNamespace = "Service_mb")
        String autoCommission,
        @WebParam(name = "registerCard", targetNamespace = "Service_mb")
        String registerCard,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param walletUa
     * @param fileName
     * @param wallet
     * @param walletIp
     * @param wlLogin
     * @param sddMandateId
     * @param language
     * @param buffer
     * @param type
     * @param version
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadFile", action = "Service_mb/UploadFile")
    @WebResult(name = "UploadFileResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "UploadFile", targetNamespace = "Service_mb", className = "lw.api.UploadFile")
    @ResponseWrapper(localName = "UploadFileResponse", targetNamespace = "Service_mb", className = "lw.api.UploadFileResponse")
    public String uploadFile(
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "fileName", targetNamespace = "Service_mb")
        String fileName,
        @WebParam(name = "type", targetNamespace = "Service_mb")
        String type,
        @WebParam(name = "buffer", targetNamespace = "Service_mb")
        byte[] buffer,
        @WebParam(name = "sddMandateId", targetNamespace = "Service_mb")
        String sddMandateId,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param walletUa
     * @param updateDate
     * @param walletIp
     * @param wlLogin
     * @param language
     * @param version
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetKycStatus", action = "Service_mb/GetKycStatus")
    @WebResult(name = "GetKycStatusResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "GetKycStatus", targetNamespace = "Service_mb", className = "lw.api.GetKycStatus")
    @ResponseWrapper(localName = "GetKycStatusResponse", targetNamespace = "Service_mb", className = "lw.api.GetKycStatusResponse")
    public String getKycStatus(
        @WebParam(name = "updateDate", targetNamespace = "Service_mb")
        String updateDate,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param walletUa
     * @param updateDate
     * @param walletIp
     * @param wlLogin
     * @param language
     * @param version
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMoneyInIBANDetails", action = "Service_mb/GetMoneyInIBANDetails")
    @WebResult(name = "GetMoneyInIBANDetailsResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "GetMoneyInIBANDetails", targetNamespace = "Service_mb", className = "lw.api.GetMoneyInIBANDetails")
    @ResponseWrapper(localName = "GetMoneyInIBANDetailsResponse", targetNamespace = "Service_mb", className = "lw.api.GetMoneyInIBANDetailsResponse")
    public String getMoneyInIBANDetails(
        @WebParam(name = "updateDate", targetNamespace = "Service_mb")
        String updateDate,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param walletUa
     * @param updateDate
     * @param walletIp
     * @param wlLogin
     * @param language
     * @param version
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetChargebacks", action = "Service_mb/GetChargebacks")
    @WebResult(name = "GetChargebacksResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "GetChargebacks", targetNamespace = "Service_mb", className = "lw.api.GetChargebacks")
    @ResponseWrapper(localName = "GetChargebacksResponse", targetNamespace = "Service_mb", className = "lw.api.GetChargebacksResponse")
    public String getChargebacks(
        @WebParam(name = "updateDate", targetNamespace = "Service_mb")
        String updateDate,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param walletUa
     * @param updateDate
     * @param chequeType
     * @param walletIp
     * @param wlLogin
     * @param language
     * @param version
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMoneyInChequeDetails", action = "Service_mb/GetMoneyInChequeDetails")
    @WebResult(name = "GetMoneyInChequeDetailsResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "GetMoneyInChequeDetails", targetNamespace = "Service_mb", className = "lw.api.GetMoneyInChequeDetails")
    @ResponseWrapper(localName = "GetMoneyInChequeDetailsResponse", targetNamespace = "Service_mb", className = "lw.api.GetMoneyInChequeDetailsResponse")
    public String getMoneyInChequeDetails(
        @WebParam(name = "updateDate", targetNamespace = "Service_mb")
        String updateDate,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa,
        @WebParam(name = "chequeType", targetNamespace = "Service_mb")
        String chequeType);

    /**
     * 
     * @param walletUa
     * @param updateDate
     * @param walletIp
     * @param wlLogin
     * @param language
     * @param version
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetMoneyInSdd", action = "Service_mb/GetMoneyInSdd")
    @WebResult(name = "GetMoneyInSddResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "GetMoneyInSdd", targetNamespace = "Service_mb", className = "lw.api.GetMoneyInSdd")
    @ResponseWrapper(localName = "GetMoneyInSddResponse", targetNamespace = "Service_mb", className = "lw.api.GetMoneyInSddResponse")
    public String getMoneyInSdd(
        @WebParam(name = "updateDate", targetNamespace = "Service_mb")
        String updateDate,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param walletUa
     * @param updateDate
     * @param walletIdStart
     * @param walletIp
     * @param wlLogin
     * @param language
     * @param walletIdEnd
     * @param version
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBalances", action = "Service_mb/GetBalances")
    @WebResult(name = "GetBalancesResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "GetBalances", targetNamespace = "Service_mb", className = "lw.api.GetBalances")
    @ResponseWrapper(localName = "GetBalancesResponse", targetNamespace = "Service_mb", className = "lw.api.GetBalancesResponse")
    public String getBalances(
        @WebParam(name = "updateDate", targetNamespace = "Service_mb")
        String updateDate,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa,
        @WebParam(name = "walletIdStart", targetNamespace = "Service_mb")
        String walletIdStart,
        @WebParam(name = "walletIdEnd", targetNamespace = "Service_mb")
        String walletIdEnd);

    /**
     * 
     * @param walletUa
     * @param walletIp
     * @param wlLogin
     * @param debitWallet
     * @param language
     * @param amountAGCOD
     * @param version
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateGiftCodeAmazon", action = "Service_mb/CreateGiftCodeAmazon")
    @WebResult(name = "CreateGiftCodeAmazonResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "CreateGiftCodeAmazon", targetNamespace = "Service_mb", className = "lw.api.CreateGiftCodeAmazon")
    @ResponseWrapper(localName = "CreateGiftCodeAmazonResponse", targetNamespace = "Service_mb", className = "lw.api.CreateGiftCodeAmazonResponse")
    public String createGiftCodeAmazon(
        @WebParam(name = "debitWallet", targetNamespace = "Service_mb")
        String debitWallet,
        @WebParam(name = "amountAGCOD", targetNamespace = "Service_mb")
        String amountAGCOD,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param walletUa
     * @param amountVCC
     * @param walletIp
     * @param wlLogin
     * @param debitWallet
     * @param language
     * @param version
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateVCC", action = "Service_mb/CreateVCC")
    @WebResult(name = "CreateVCCResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "CreateVCC", targetNamespace = "Service_mb", className = "lw.api.CreateVCC")
    @ResponseWrapper(localName = "CreateVCCResponse", targetNamespace = "Service_mb", className = "lw.api.CreateVCCResponse")
    public String createVCC(
        @WebParam(name = "debitWallet", targetNamespace = "Service_mb")
        String debitWallet,
        @WebParam(name = "amountVCC", targetNamespace = "Service_mb")
        String amountVCC,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param wallet
     * @param amountCom
     * @param wlLogin
     * @param language
     * @param amountTot
     * @param autoCommission
     * @param version
     * @param wlPass
     * @param walletUa
     * @param issuerId
     * @param walletIp
     * @param comment
     * @param returnUrl
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MoneyInIDealInit", action = "Service_mb/MoneyInIDealInit")
    @WebResult(name = "MoneyInIDealInitResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "MoneyInIDealInit", targetNamespace = "Service_mb", className = "lw.api.MoneyInIDealInit")
    @ResponseWrapper(localName = "MoneyInIDealInitResponse", targetNamespace = "Service_mb", className = "lw.api.MoneyInIDealInitResponse")
    public String moneyInIDealInit(
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "amountTot", targetNamespace = "Service_mb")
        String amountTot,
        @WebParam(name = "amountCom", targetNamespace = "Service_mb")
        String amountCom,
        @WebParam(name = "comment", targetNamespace = "Service_mb")
        String comment,
        @WebParam(name = "returnUrl", targetNamespace = "Service_mb")
        String returnUrl,
        @WebParam(name = "autoCommission", targetNamespace = "Service_mb")
        String autoCommission,
        @WebParam(name = "issuerId", targetNamespace = "Service_mb")
        String issuerId,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param walletUa
     * @param walletIp
     * @param wlLogin
     * @param language
     * @param version
     * @param transactionId
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MoneyInIDealConfirm", action = "Service_mb/MoneyInIDealConfirm")
    @WebResult(name = "MoneyInIDealConfirmResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "MoneyInIDealConfirm", targetNamespace = "Service_mb", className = "lw.api.MoneyInIDealConfirm")
    @ResponseWrapper(localName = "MoneyInIDealConfirmResponse", targetNamespace = "Service_mb", className = "lw.api.MoneyInIDealConfirmResponse")
    public String moneyInIDealConfirm(
        @WebParam(name = "transactionId", targetNamespace = "Service_mb")
        String transactionId,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param wallet
     * @param amountCom
     * @param wlLogin
     * @param sddMandateId
     * @param language
     * @param amountTot
     * @param autoCommission
     * @param collectionDate
     * @param version
     * @param wlPass
     * @param walletUa
     * @param walletIp
     * @param comment
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MoneyInSddInit", action = "Service_mb/MoneyInSddInit")
    @WebResult(name = "MoneyInSddInitResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "MoneyInSddInit", targetNamespace = "Service_mb", className = "lw.api.MoneyInSddInit")
    @ResponseWrapper(localName = "MoneyInSddInitResponse", targetNamespace = "Service_mb", className = "lw.api.MoneyInSddInitResponse")
    public String moneyInSddInit(
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "amountTot", targetNamespace = "Service_mb")
        String amountTot,
        @WebParam(name = "amountCom", targetNamespace = "Service_mb")
        String amountCom,
        @WebParam(name = "comment", targetNamespace = "Service_mb")
        String comment,
        @WebParam(name = "autoCommission", targetNamespace = "Service_mb")
        String autoCommission,
        @WebParam(name = "sddMandateId", targetNamespace = "Service_mb")
        String sddMandateId,
        @WebParam(name = "collectionDate", targetNamespace = "Service_mb")
        String collectionDate,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param wallet
     * @param amountCom
     * @param wlLogin
     * @param language
     * @param transferId
     * @param amountTot
     * @param autoCommission
     * @param version
     * @param wlPass
     * @param walletUa
     * @param chequeType
     * @param partner
     * @param walletIp
     * @param comment
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MoneyInChequeInit", action = "Service_mb/MoneyInChequeInit")
    @WebResult(name = "MoneyInChequeInitResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "MoneyInChequeInit", targetNamespace = "Service_mb", className = "lw.api.MoneyInChequeInit")
    @ResponseWrapper(localName = "MoneyInChequeInitResponse", targetNamespace = "Service_mb", className = "lw.api.MoneyInChequeInitResponse")
    public String moneyInChequeInit(
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "amountTot", targetNamespace = "Service_mb")
        String amountTot,
        @WebParam(name = "amountCom", targetNamespace = "Service_mb")
        String amountCom,
        @WebParam(name = "comment", targetNamespace = "Service_mb")
        String comment,
        @WebParam(name = "autoCommission", targetNamespace = "Service_mb")
        String autoCommission,
        @WebParam(name = "transferId", targetNamespace = "Service_mb")
        String transferId,
        @WebParam(name = "partner", targetNamespace = "Service_mb")
        String partner,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa,
        @WebParam(name = "chequeType", targetNamespace = "Service_mb")
        String chequeType);

    /**
     * 
     * @param wallet
     * @param amountCom
     * @param wlLogin
     * @param wkToken
     * @param language
     * @param amountTot
     * @param version
     * @param wlPass
     * @param idTicket
     * @param walletUa
     * @param walletIp
     * @param isNeocode
     * @param comment
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MoneyInNeosurf", action = "Service_mb/MoneyInNeosurf")
    @WebResult(name = "MoneyInNeosurfResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "MoneyInNeosurf", targetNamespace = "Service_mb", className = "lw.api.MoneyInNeosurf")
    @ResponseWrapper(localName = "MoneyInNeosurfResponse", targetNamespace = "Service_mb", className = "lw.api.MoneyInNeosurfResponse")
    public String moneyInNeosurf(
        @WebParam(name = "wkToken", targetNamespace = "Service_mb")
        String wkToken,
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "amountTot", targetNamespace = "Service_mb")
        String amountTot,
        @WebParam(name = "amountCom", targetNamespace = "Service_mb")
        String amountCom,
        @WebParam(name = "comment", targetNamespace = "Service_mb")
        String comment,
        @WebParam(name = "idTicket", targetNamespace = "Service_mb")
        String idTicket,
        @WebParam(name = "isNeocode", targetNamespace = "Service_mb")
        String isNeocode,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param walletUa
     * @param walletIp
     * @param wlLogin
     * @param language
     * @param version
     * @param wlPass
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetWizypayAds", action = "Service_mb/GetWizypayAds")
    @WebResult(name = "GetWizypayAdsResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "GetWizypayAds", targetNamespace = "Service_mb", className = "lw.api.GetWizypayAds")
    @ResponseWrapper(localName = "GetWizypayAdsResponse", targetNamespace = "Service_mb", className = "lw.api.GetWizypayAdsResponse")
    public String getWizypayAds(
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param wallet
     * @param amountCom
     * @param wlLogin
     * @param wkToken
     * @param language
     * @param amountTot
     * @param autoCommission
     * @param version
     * @param wlPass
     * @param walletUa
     * @param walletIp
     * @param comment
     * @param returnUrl
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MoneyInSofortInit", action = "Service_mb/MoneyInSofortInit")
    @WebResult(name = "MoneyInSofortInitResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "MoneyInSofortInit", targetNamespace = "Service_mb", className = "lw.api.MoneyInSofortInit")
    @ResponseWrapper(localName = "MoneyInSofortInitResponse", targetNamespace = "Service_mb", className = "lw.api.MoneyInSofortInitResponse")
    public String moneyInSofortInit(
        @WebParam(name = "wkToken", targetNamespace = "Service_mb")
        String wkToken,
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "amountTot", targetNamespace = "Service_mb")
        String amountTot,
        @WebParam(name = "amountCom", targetNamespace = "Service_mb")
        String amountCom,
        @WebParam(name = "comment", targetNamespace = "Service_mb")
        String comment,
        @WebParam(name = "returnUrl", targetNamespace = "Service_mb")
        String returnUrl,
        @WebParam(name = "autoCommission", targetNamespace = "Service_mb")
        String autoCommission,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param wallet
     * @param amountCom
     * @param wlLogin
     * @param wkToken
     * @param language
     * @param amountTot
     * @param autoCommission
     * @param version
     * @param wlPass
     * @param walletUa
     * @param walletIp
     * @param comment
     * @param returnUrl
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MoneyInMultibancoInit", action = "Service_mb/MoneyInMultibancoInit")
    @WebResult(name = "MoneyInMultibancoInitResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "MoneyInMultibancoInit", targetNamespace = "Service_mb", className = "lw.api.MoneyInMultibancoInit")
    @ResponseWrapper(localName = "MoneyInMultibancoInitResponse", targetNamespace = "Service_mb", className = "lw.api.MoneyInMultibancoInitResponse")
    public String moneyInMultibancoInit(
        @WebParam(name = "wkToken", targetNamespace = "Service_mb")
        String wkToken,
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "amountTot", targetNamespace = "Service_mb")
        String amountTot,
        @WebParam(name = "amountCom", targetNamespace = "Service_mb")
        String amountCom,
        @WebParam(name = "comment", targetNamespace = "Service_mb")
        String comment,
        @WebParam(name = "returnUrl", targetNamespace = "Service_mb")
        String returnUrl,
        @WebParam(name = "autoCommission", targetNamespace = "Service_mb")
        String autoCommission,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param wallet
     * @param amountCom
     * @param wlLogin
     * @param wkToken
     * @param language
     * @param amountTot
     * @param autoCommission
     * @param version
     * @param wlPass
     * @param walletUa
     * @param walletIp
     * @param comment
     * @param returnUrl
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MoneyInPayshopInit", action = "Service_mb/MoneyInPayshopInit")
    @WebResult(name = "MoneyInPayshopInitResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "MoneyInPayshopInit", targetNamespace = "Service_mb", className = "lw.api.MoneyInPayshopInit")
    @ResponseWrapper(localName = "MoneyInPayshopInitResponse", targetNamespace = "Service_mb", className = "lw.api.MoneyInPayshopInitResponse")
    public String moneyInPayshopInit(
        @WebParam(name = "wkToken", targetNamespace = "Service_mb")
        String wkToken,
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "amountTot", targetNamespace = "Service_mb")
        String amountTot,
        @WebParam(name = "amountCom", targetNamespace = "Service_mb")
        String amountCom,
        @WebParam(name = "comment", targetNamespace = "Service_mb")
        String comment,
        @WebParam(name = "returnUrl", targetNamespace = "Service_mb")
        String returnUrl,
        @WebParam(name = "autoCommission", targetNamespace = "Service_mb")
        String autoCommission,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param wallet
     * @param amountCom
     * @param wlLogin
     * @param wkToken
     * @param language
     * @param amountTot
     * @param autoCommission
     * @param version
     * @param wlPass
     * @param walletUa
     * @param walletIp
     * @param phone
     * @param comment
     * @param returnUrl
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MoneyInMbwayInit", action = "Service_mb/MoneyInMbwayInit")
    @WebResult(name = "MoneyInMbwayInitResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "MoneyInMbwayInit", targetNamespace = "Service_mb", className = "lw.api.MoneyInMbwayInit")
    @ResponseWrapper(localName = "MoneyInMbwayInitResponse", targetNamespace = "Service_mb", className = "lw.api.MoneyInMbwayInitResponse")
    public String moneyInMbwayInit(
        @WebParam(name = "wkToken", targetNamespace = "Service_mb")
        String wkToken,
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "amountTot", targetNamespace = "Service_mb")
        String amountTot,
        @WebParam(name = "amountCom", targetNamespace = "Service_mb")
        String amountCom,
        @WebParam(name = "comment", targetNamespace = "Service_mb")
        String comment,
        @WebParam(name = "returnUrl", targetNamespace = "Service_mb")
        String returnUrl,
        @WebParam(name = "autoCommission", targetNamespace = "Service_mb")
        String autoCommission,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa,
        @WebParam(name = "phone", targetNamespace = "Service_mb")
        String phone);

    /**
     * 
     * @param wallet
     * @param amountCom
     * @param wlLogin
     * @param wkToken
     * @param language
     * @param amountTot
     * @param autoCommission
     * @param version
     * @param wlPass
     * @param walletUa
     * @param walletIp
     * @param comment
     * @param returnUrl
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MoneyInPayTrailInit", action = "Service_mb/MoneyInPayTrailInit")
    @WebResult(name = "MoneyInPayTrailInitResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "MoneyInPayTrailInit", targetNamespace = "Service_mb", className = "lw.api.MoneyInPayTrailInit")
    @ResponseWrapper(localName = "MoneyInPayTrailInitResponse", targetNamespace = "Service_mb", className = "lw.api.MoneyInPayTrailInitResponse")
    public String moneyInPayTrailInit(
        @WebParam(name = "wkToken", targetNamespace = "Service_mb")
        String wkToken,
        @WebParam(name = "wallet", targetNamespace = "Service_mb")
        String wallet,
        @WebParam(name = "amountTot", targetNamespace = "Service_mb")
        String amountTot,
        @WebParam(name = "amountCom", targetNamespace = "Service_mb")
        String amountCom,
        @WebParam(name = "comment", targetNamespace = "Service_mb")
        String comment,
        @WebParam(name = "returnUrl", targetNamespace = "Service_mb")
        String returnUrl,
        @WebParam(name = "autoCommission", targetNamespace = "Service_mb")
        String autoCommission,
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa);

    /**
     * 
     * @param walletPayer
     * @param emailPayer
     * @param walletReceiver
     * @param amountCom
     * @param firstNamePayer
     * @param wlLogin
     * @param language
     * @param amountTot
     * @param version
     * @param wlPass
     * @param lastNamePayer
     * @param walletUa
     * @param walletIp
     * @param comment
     * @param style
     * @param optId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreatePaymentForm", action = "Service_mb/CreatePaymentForm")
    @WebResult(name = "CreatePaymentFormResult", targetNamespace = "Service_mb")
    @RequestWrapper(localName = "CreatePaymentForm", targetNamespace = "Service_mb", className = "lw.api.CreatePaymentForm")
    @ResponseWrapper(localName = "CreatePaymentFormResponse", targetNamespace = "Service_mb", className = "lw.api.CreatePaymentFormResponse")
    public String createPaymentForm(
        @WebParam(name = "wlLogin", targetNamespace = "Service_mb")
        String wlLogin,
        @WebParam(name = "wlPass", targetNamespace = "Service_mb")
        String wlPass,
        @WebParam(name = "optId", targetNamespace = "Service_mb")
        String optId,
        @WebParam(name = "walletPayer", targetNamespace = "Service_mb")
        String walletPayer,
        @WebParam(name = "walletReceiver", targetNamespace = "Service_mb")
        String walletReceiver,
        @WebParam(name = "walletIp", targetNamespace = "Service_mb")
        String walletIp,
        @WebParam(name = "walletUa", targetNamespace = "Service_mb")
        String walletUa,
        @WebParam(name = "amountTot", targetNamespace = "Service_mb")
        String amountTot,
        @WebParam(name = "amountCom", targetNamespace = "Service_mb")
        String amountCom,
        @WebParam(name = "comment", targetNamespace = "Service_mb")
        String comment,
        @WebParam(name = "language", targetNamespace = "Service_mb")
        String language,
        @WebParam(name = "version", targetNamespace = "Service_mb")
        String version,
        @WebParam(name = "firstNamePayer", targetNamespace = "Service_mb")
        String firstNamePayer,
        @WebParam(name = "lastNamePayer", targetNamespace = "Service_mb")
        String lastNamePayer,
        @WebParam(name = "emailPayer", targetNamespace = "Service_mb")
        String emailPayer,
        @WebParam(name = "style", targetNamespace = "Service_mb")
        String style);

}
